# -*- coding: utf-8 -*-
"""MGModEditor 功能描述 i18n 生成器（可重复运行，幂等）。

向 5 份语言包 JSON（res/i18n/*.json）插入功能描述键（Tier-1 114 + Tier-2 45 = 159 键）。
- 文本级插入：保留原文件 meta 单行格式 / CRLF 行尾，diff 最小化；
- 幂等：已存在的键跳过，重跑安全；
- 术语已按 SPT_Data/database/locales/global 官方语料对齐（地图名/T7/幸运Scav垃圾箱/安全箱等）；
- 重建方式：tools/ 下读取 5 份 JSON + tier2_data.py 重新生成本文件。
"""
import json
import os
import re

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
I18N_DIR = os.path.join(BASE, 'MGModEditor', 'res', 'i18n')
LANGS = ['zh-CN', 'en-US', 'ru-RU', 'fr-FR', 'jp-JP']

# key -> {lang: text}，zh-CN 为基线
DATA = {
    "Raid.Desc.AiHealth": {"zh-CN": "调整战局内所有 AI（Scav/BOSS/PMC）的基础血量倍率，数值越高越难击杀。", "en-US": "Adjusts the base health multiplier of all AI (Scavs, bosses, PMCs) in raid. Higher values make them harder to kill.", "ru-RU": "Регулирует множитель базового здоровья всех AI (Scav, боссы, PMC) в рейде. Чем выше значение, тем сложнее их убить.", "fr-FR": "Ajuste le multiplicateur de santé de base de tous les IA (Scavs, boss, PMC) en raid. Plus la valeur est élevée, plus ils sont difficiles à tuer.", "jp-JP": "レイド内の全AI（Scav/ボス/PMC）の基礎体力倍率を調整します。値が高いほど倒しにくくなります。"},
    "Raid.Desc.AiSpawnNumber": {"zh-CN": "调整战局内 AI 的刷新数量上限，影响同屏敌人的密度。", "en-US": "Adjusts the AI spawn limit in raid, controlling how many enemies appear on screen.", "ru-RU": "Регулирует лимит спавна AI в рейде, влияя на плотность врагов на экране.", "fr-FR": "Règle la limite d'apparition des IA en raid, contrôlant la densité d'ennemis à l'écran.", "jp-JP": "レイド内のAI出現上限を調整します。画面内の敵の密度に影響します。"},
    "Raid.Desc.USECRatio": {"zh-CN": "调整战局中 USEC 与 Bear 阵营 PMC 的刷新比例。", "en-US": "Adjusts the spawn ratio between USEC and Bear PMCs in raid.", "ru-RU": "Регулирует соотношение появления PMC фракций USEC и Bear в рейде.", "fr-FR": "Règle le ratio d'apparition entre les PMC USEC et Bear en raid.", "jp-JP": "レイド内のUSECとBearのPMC出現比率を調整します。"},
    "Raid.Desc.AiNamePool": {"zh-CN": "为 AI 启用扩展名字库，昵称不再局限于原版名单。", "en-US": "Enables an expanded name pool for AI; nicknames are no longer limited to the vanilla list.", "ru-RU": "Включает расширенный набор имён для AI; ники больше не ограничены списком из ванилы.", "fr-FR": "Active un répertoire de noms élargi pour les IA ; les surnoms ne se limitent plus à la liste d'origine.", "jp-JP": "AIに拡張名前プールを有効にします。ニックネームがバニラのリストに限定されなくなります。"},
    "Raid.Desc.PmcTacticalSquad": {"zh-CN": "开启后 PMC 会以战术小队形式行动，相互配合进攻与索敌。", "en-US": "When enabled, PMCs operate in tactical squads, coordinating attacks and patrols.", "ru-RU": "При включении PMC действуют тактическими отрядами, координируя атаки и разведку.", "fr-FR": "Une fois activé, les PMC opèrent en escouades tactiques, coordonnant attaques et reconnaissance.", "jp-JP": "有効にするとPMCが戦術小隊として行動し、攻撃と索敵を連携します。"},
    "Raid.Desc.PmcRoar": {"zh-CN": "开启后 PMC 在战局内会随机发出怒吼语音，增强战场氛围。", "en-US": "When enabled, PMCs randomly roar in raid for a more immersive battlefield.", "ru-RU": "При включении PMC случайно выкрикивают боевые кличи в рейде для большего погружения.", "fr-FR": "Une fois activé, les PMC poussent des cris de guerre aléatoires en raid pour un champ de bataille plus immersif.", "jp-JP": "有効にするとPMCがレイド中にランダムに怒号を発し、戦場の臨場感が高まります。"},
    "Raid.Desc.DefaultOptions": {"zh-CN": "开启后可自定义战局默认的 AI 数量、难度、BOSS、Scav 内战与标记诅咒等选项。", "en-US": "When enabled, you can customize default raid options: AI amount, difficulty, bosses, Scav wars, and marked-and-cursed.", "ru-RU": "При включении можно настраивать параметры рейда по умолчанию: количество AI, сложность, боссы, войны Scav и отметка проклятых.", "fr-FR": "Une fois activé, vous pouvez personnaliser les options de raid par défaut : nombre d'IA, difficulté, boss, guerres Scav et marquage maudit.", "jp-JP": "有効にすると、デフォルトのAI数・難易度・ボス・Scav内戦・マークド＆カースドなどをカスタマイズできます。"},
    "Raid.Desc.AiAmount": {"zh-CN": "设置战局 AI 数量档位（联机人数/无/低/中/高/尸潮），需先开启“默认选项自定义”。", "en-US": "Sets the AI amount tier (like online / none / low / medium / high / horde). Requires “Default options” to be enabled.", "ru-RU": "Задаёт уровень количества AI (как в онлайне/нет/низко/средне/высоко/орда). Требует включённой настройки «Параметры по умолчанию».", "fr-FR": "Définit le palier de nombre d'IA (comme en ligne / aucun / faible / moyen / élevé / horde). Nécessite l'activation des « Options par défaut ».", "jp-JP": "レイドのAI数を設定します（オンライン同等/なし/低/中/高/大群）。「デフォルト設定」の有効化が必要です。"},
    "Raid.Desc.AiDifficulty": {"zh-CN": "设置战局 AI 难度档位（联机/简单/中等/困难/不可能/随机）。", "en-US": "Sets the AI difficulty tier (online / easy / medium / hard / impossible / random).", "ru-RU": "Задаёт уровень сложности AI (как в онлайне/легко/средне/сложно/невозможно/случайно).", "fr-FR": "Définit le palier de difficulté des IA (en ligne / facile / moyen / difficile / impossible / aléatoire).", "jp-JP": "レイドのAI難易度を設定します（オンライン同等/簡単/普通/困難/不可能/ランダム）。"},
    "Raid.Desc.EnableBoss": {"zh-CN": "是否在战局中启用 BOSS 及其护卫小队。", "en-US": "Whether to enable bosses and their guards in raid.", "ru-RU": "Включает ли боссов и их охрану в рейде.", "fr-FR": "Active ou non les boss et leur escorte en raid.", "jp-JP": "レイド内でボスとその護衛を有効にするか設定します。"},
    "Raid.Desc.ScavCivilWar": {"zh-CN": "开启后 Scav 会互相攻击，形成阵营内战。", "en-US": "When enabled, Scavs attack each other, causing factional civil war.", "ru-RU": "При включении Scav атакуют друг друга, устраивая гражданскую войну.", "fr-FR": "Une fois activé, les Scavs s'attaquent entre eux, déclenchant une guerre civile.", "jp-JP": "有効にするとScav同士が攻撃し合い、内戦状態になります。"},
    "Raid.Desc.MarkedCursed": {"zh-CN": "开启后部分 AI 会主动锁定并追杀玩家，营造高威胁遭遇。", "en-US": "When enabled, some AI actively hunt the player, creating high-threat encounters.", "ru-RU": "При включении часть AI активно охотится на игрока, создавая опасные столкновения.", "fr-FR": "Une fois activé, certains IA traquent activement le joueur, créant des rencontres à haut risque.", "jp-JP": "有効にすると一部のAIがプレイヤーを積極的に追跡し、高脅威の遭遇を生み出します。"},
    "Raid.Desc.RaidTime": {"zh-CN": "设置单局战场的最大时长，到期自动结算撤离。", "en-US": "Sets the maximum raid duration; the raid ends automatically when time expires.", "ru-RU": "Задаёт максимальную длительность рейда; по истечении времени рейд завершается автоматически.", "fr-FR": "Définit la durée maximale du raid ; le raid se termine automatiquement à l'échéance.", "jp-JP": "レイドの最大時間を設定します。時間切れで自動的に終了・撤収します。"},
    "Raid.Desc.BossSpawnRate": {"zh-CN": "调整 BOSS 的刷新概率，数值越高越容易遇到。", "en-US": "Adjusts boss spawn probability; higher values mean more frequent boss encounters.", "ru-RU": "Регулирует вероятность появления боссов; чем выше значение, тем чаще встречи с ними.", "fr-FR": "Règle la probabilité d'apparition des boss ; plus la valeur est élevée, plus ils sont fréquents.", "jp-JP": "ボスの出現確率を調整します。値が高いほど遭遇しやすくなります。"},
    "Raid.Desc.AirdropType": {"zh-CN": "设置空投补给的内容倾向（武器/物资/医疗/混合等）。", "en-US": "Sets the airdrop content preference (weapons / supplies / medical / mixed, etc.).", "ru-RU": "Задаёт содержимое аирдропов (оружие/припасы/медицина/смешанное и т.д.).", "fr-FR": "Définit le contenu des largages (armes / fournitures / médical / mixte, etc.).", "jp-JP": "エアドロップの内容傾向を設定します（武器/物資/医療/混合など）。"},
    "Raid.Desc.AlwaysExtractSwitch": {"zh-CN": "开启后所有撤离点的拉闸必定成功。", "en-US": "When enabled, all extract switches always work on the first pull.", "ru-RU": "При включении рубильники всех выходов всегда срабатывают с первой попытки.", "fr-FR": "Une fois activé, les interrupteurs de sortie fonctionnent toujours du premier coup.", "jp-JP": "有効にすると全ての脱出地点のレバーが必ず成功します。"},
    "Raid.Desc.AlwaysExtractable": {"zh-CN": "开启后所有撤离点必定处于可用状态。", "en-US": "When enabled, all extracts are always available.", "ru-RU": "При включении все выходы всегда доступны.", "fr-FR": "Une fois activé, toutes les sorties sont toujours disponibles.", "jp-JP": "有効にすると全ての脱出地点が常に使用可能になります。"},
    "Raid.Desc.UnlimitedExtractTime": {"zh-CN": "撤离不再受倒计时限制，随时可撤离。", "en-US": "Extracts are no longer limited by a countdown; you can extract at any time.", "ru-RU": "Выходы больше не ограничены таймером; можно выйти в любой момент.", "fr-FR": "Les sorties ne sont plus limitées par un compte à rebours ; vous pouvez partir à tout moment.", "jp-JP": "脱出のカウントダウン制限がなくなり、いつでも脱出できます。"},
    "Raid.Desc.ScavNoCooldown": {"zh-CN": "移除以 Scav 身份进入战局的冷却时间。", "en-US": "Removes the cooldown for entering raids as a Scav.", "ru-RU": "Убирает перезарядку входа в рейд за Scav.", "fr-FR": "Supprime le temps de recharge pour entrer en raid en Scav.", "jp-JP": "Scavとしてレイドに入る際のクールダウンを撤廃します。"},
    "Raid.Desc.ScavGearBoost": {"zh-CN": "提升 Scav 出生时的装备质量与携带物品价值。", "en-US": "Improves the quality of Scav starting gear and the value of carried loot.", "ru-RU": "Улучшает стартовое снаряжение Scav и ценность носимого лута.", "fr-FR": "Améliore l'équipement de départ des Scavs et la valeur des objets emportés.", "jp-JP": "Scavの初期装備の質と所持品の価値を向上させます。"},
    "Raid.Desc.NoLootLoss": {"zh-CN": "死亡后背包与装备不再掉落，战局内保留全部战利品。", "en-US": "On death, your backpack and equipment are no longer lost; all loot is kept.", "ru-RU": "После смерти рюкзак и снаряжение не теряются; весь лут сохраняется.", "fr-FR": "À la mort, votre sac et votre équipement ne sont plus perdus ; tout le butin est conservé.", "jp-JP": "死亡してもバックパックと装備を失いません。獲得した戦利品は全て保持されます。"},
    "Raid.Desc.MapRefreshConfig": {"zh-CN": "开启后按地图独立优化 AI 刷新配置（BotSystem）。", "en-US": "When enabled, AI spawn configuration is optimized per map (BotSystem).", "ru-RU": "При включении конфигурация спавна AI оптимизируется отдельно для каждой карты (BotSystem).", "fr-FR": "Une fois activé, la configuration d'apparition des IA est optimisée par carte (BotSystem).", "jp-JP": "有効にするとAI出現設定がマップごとに個別最適化されます（BotSystem）。"},
    "Raid.Desc.MapBotDifficulty": {"zh-CN": "按地图设置 AI 难度档位，覆盖全局难度。", "en-US": "Sets the AI difficulty tier per map, overriding the global difficulty.", "ru-RU": "Задаёт уровень сложности AI по картам, переопределяя глобальную сложность.", "fr-FR": "Définit le palier de difficulté des IA par carte, en remplaçant la difficulté globale.", "jp-JP": "マップごとにAI難易度を設定し、グローバル難易度を上書きします。"},
    "Raid.Desc.GlobalWeather": {"zh-CN": "选择天气模式（原版/晴朗/雨天/风暴/大雾/极端/自定义）。", "en-US": "Selects the weather mode (vanilla / clear / rainy / storm / misty / extreme / custom).", "ru-RU": "Выбор режима погоды (ванила/ясно/дождь/шторм/туман/экстрим/кастом).", "fr-FR": "Choisit le mode météo (original / dégagé / pluvieux / tempête / brumeux / extrême / personnalisé).", "jp-JP": "天候モードを選択します（バニラ/晴れ/雨/嵐/霧/極端/カスタム）。"},
    "Raid.Desc.Cloud": {"zh-CN": "调整云层覆盖密度，需全局天气非“原版”时生效。", "en-US": "Adjusts cloud cover density; takes effect when global weather is not “vanilla”.", "ru-RU": "Регулирует плотность облачности; действует, когда глобальная погода не «ванила».", "fr-FR": "Règle la densité de la couverture nuageuse ; actif quand la météo globale n'est pas « original ».", "jp-JP": "雲量を調整します。グローバル天候が「バニラ」以外の時に有効です。"},
    "Raid.Desc.Wind": {"zh-CN": "调整风速等级，影响弹道与声音传播。", "en-US": "Adjusts wind strength, affecting ballistics and sound propagation.", "ru-RU": "Регулирует силу ветра, влияя на баллистику и распространение звука.", "fr-FR": "Règle la force du vent, influant sur la balistique et la propagation du son.", "jp-JP": "風の強さを調整します。弾道と音の伝播に影響します。"},
    "Raid.Desc.Rain": {"zh-CN": "调整降雨强度。", "en-US": "Adjusts rain intensity.", "ru-RU": "Регулирует интенсивность дождя.", "fr-FR": "Règle l'intensité de la pluie.", "jp-JP": "雨の強さを調整します。"},
    "Raid.Desc.Fog": {"zh-CN": "调整雾的浓度。", "en-US": "Adjusts fog density.", "ru-RU": "Регулирует плотность тумана.", "fr-FR": "Règle la densité du brouillard.", "jp-JP": "霧の濃さを調整します。"},
    "Raid.Desc.GlobalLoot": {"zh-CN": "调整全地图战利品刷新倍率。", "en-US": "Adjusts the global loot spawn multiplier across all maps.", "ru-RU": "Регулирует глобальный множитель спавна лута на всех картах.", "fr-FR": "Règle le multiplicateur global d'apparition du butin sur toutes les cartes.", "jp-JP": "全マップの戦利品出現倍率を調整します。"},
    "Raid.Desc.ContainerLoot": {"zh-CN": "调整容器内战利品的刷新倍率。", "en-US": "Adjusts the loot spawn multiplier inside containers.", "ru-RU": "Регулирует множитель спавна лута в контейнерах.", "fr-FR": "Règle le multiplicateur d'apparition du butin dans les conteneurs.", "jp-JP": "コンテナ内の戦利品出現倍率を調整します。"},
    "Raid.Desc.GroundLoot": {"zh-CN": "调整地面散落战利品的刷新倍率。", "en-US": "Adjusts the loot spawn multiplier for loose ground loot.", "ru-RU": "Регулирует множитель спавна лута на земле.", "fr-FR": "Règle le multiplicateur d'apparition du butin au sol.", "jp-JP": "地面に落ちている戦利品の出現倍率を調整します。"},
    "Raid.Desc.ValuableLoot": {"zh-CN": "调整高价值物品（钥匙、情报等）的刷新倍率。", "en-US": "Adjusts the spawn multiplier for valuable items (keys, intel, etc.).", "ru-RU": "Регулирует множитель спавна ценных предметов (ключи, разведданные и т.д.).", "fr-FR": "Règle le multiplicateur d'apparition des objets de valeur (clés, renseignements, etc.).", "jp-JP": "高価値アイテム（鍵、情報など）の出現倍率を調整します。"},
    "Raid.Desc.DisableRandomContainers": {"zh-CN": "开启后关闭容器的随机内容生成，容器内容固定。", "en-US": "When enabled, containers no longer generate random contents; their contents become fixed.", "ru-RU": "При включении контейнеры больше не генерируют случайное содержимое; оно становится фиксированным.", "fr-FR": "Une fois activé, les conteneurs ne génèrent plus de contenu aléatoire ; leur contenu devient fixe.", "jp-JP": "有効にするとコンテナのランダム生成が無効になり、中身が固定されます。"},
    "Raid.Desc.Map.Customs": {"zh-CN": "开启后海关地图中的物品可回保，死亡或丢弃后由保险返还。", "en-US": "When enabled, items lost on Customs can be returned by insurance after death or discard.", "ru-RU": "При включении предметы, потерянные на карте Таможня, могут быть возвращены страховкой.", "fr-FR": "Une fois activé, les objets perdus sur Customs peuvent être rendus par l'assurance.", "jp-JP": "有効にすると、Customsで失ったアイテムが保険で返還される可能性があります。"},
    "Raid.Desc.Map.Factory": {"zh-CN": "开启后工厂地图中的物品可回保，死亡或丢弃后由保险返还。", "en-US": "When enabled, items lost on Factory can be returned by insurance after death or discard.", "ru-RU": "При включении предметы, потерянные на карте Завод, могут быть возвращены страховкой.", "fr-FR": "Une fois activé, les objets perdus sur Factory peuvent être rendus par l'assurance.", "jp-JP": "有効にすると、Factoryで失ったアイテムが保険で返還される可能性があります。"},
    "Raid.Desc.Map.Interchange": {"zh-CN": "开启后立交桥地图中的物品可回保，死亡或丢弃后由保险返还。", "en-US": "When enabled, items lost on Interchange can be returned by insurance after death or discard.", "ru-RU": "При включении предметы, потерянные на карте Развязка, могут быть возвращены страховкой.", "fr-FR": "Une fois activé, les objets perdus sur Interchange peuvent être rendus par l'assurance.", "jp-JP": "有効にすると、Interchangeで失ったアイテムが保険で返還される可能性があります。"},
    "Raid.Desc.Map.Labs": {"zh-CN": "开启后实验室地图中的物品可回保，死亡或丢弃后由保险返还。", "en-US": "When enabled, items lost in the Lab can be returned by insurance after death or discard.", "ru-RU": "При включении предметы, потерянные на карте Лаборатория, могут быть возвращены страховкой.", "fr-FR": "Une fois activé, les objets perdus dans The Lab peuvent être rendus par l'assurance.", "jp-JP": "有効にすると、The Labで失ったアイテムが保険で返還される可能性があります。"},
    "Raid.Desc.Map.Lighthouse": {"zh-CN": "开启后灯塔地图中的物品可回保，死亡或丢弃后由保险返还。", "en-US": "When enabled, items lost on Lighthouse can be returned by insurance after death or discard.", "ru-RU": "При включении предметы, потерянные на карте Маяк, могут быть возвращены страховкой.", "fr-FR": "Une fois activé, les objets perdus sur Lighthouse peuvent être rendus par l'assurance.", "jp-JP": "有効にすると、Lighthouseで失ったアイテムが保険で返還される可能性があります。"},
    "Raid.Desc.Map.Reserve": {"zh-CN": "开启后储备站地图中的物品可回保，死亡或丢弃后由保险返还。", "en-US": "When enabled, items lost on Reserve can be returned by insurance after death or discard.", "ru-RU": "При включении предметы, потерянные на карте Резерв, могут быть возвращены страховкой.", "fr-FR": "Une fois activé, les objets perdus sur Reserve peuvent être rendus par l'assurance.", "jp-JP": "有効にすると、Reserveで失ったアイテムが保険で返還される可能性があります。"},
    "Raid.Desc.Map.GroundZero": {"zh-CN": "开启后中心区地图中的物品可回保，死亡或丢弃后由保险返还。", "en-US": "When enabled, items lost on Ground Zero can be returned by insurance after death or discard.", "ru-RU": "При включении предметы, потерянные на карте Эпицентр, могут быть возвращены страховкой.", "fr-FR": "Une fois activé, les objets perdus sur Ground Zero peuvent être rendus par l'assurance.", "jp-JP": "有効にすると、Ground Zeroで失ったアイテムが保険で返還される可能性があります。"},
    "Raid.Desc.Map.Shoreline": {"zh-CN": "开启后海岸线地图中的物品可回保，死亡或丢弃后由保险返还。", "en-US": "When enabled, items lost on Shoreline can be returned by insurance after death or discard.", "ru-RU": "При включении предметы, потерянные на карте Берег, могут быть возвращены страховкой.", "fr-FR": "Une fois activé, les objets perdus sur Shoreline peuvent être rendus par l'assurance.", "jp-JP": "有効にすると、Shorelineで失ったアイテムが保険で返還される可能性があります。"},
    "Raid.Desc.Map.Streets": {"zh-CN": "开启后塔科夫街区地图中的物品可回保，死亡或丢弃后由保险返还。", "en-US": "When enabled, items lost on Streets of Tarkov can be returned by insurance after death or discard.", "ru-RU": "При включении предметы, потерянные на карте «Улицы Таркова», могут быть возвращены страховкой.", "fr-FR": "Une fois activé, les objets perdus sur Streets of Tarkov peuvent être rendus par l'assurance.", "jp-JP": "有効にすると、Streets of Tarkovで失ったアイテムが保険で返還される可能性があります。"},
    "Raid.Desc.Map.Woods": {"zh-CN": "开启后森林地图中的物品可回保，死亡或丢弃后由保险返还。", "en-US": "When enabled, items lost on Woods can be returned by insurance after death or discard.", "ru-RU": "При включении предметы, потерянные на карте Лес, могут быть возвращены страховкой.", "fr-FR": "Une fois activé, les objets perdus sur Woods peuvent être rendus par l'assurance.", "jp-JP": "有効にすると、Woodsで失ったアイテムが保険で返還される可能性があります。"},
    "Raid.Desc.Map.Labyrinth": {"zh-CN": "开启后 The Labyrinth 地图中的物品可回保，死亡或丢弃后由保险返还。", "en-US": "When enabled, items lost on The Labyrinth can be returned by insurance after death or discard.", "ru-RU": "При включении предметы, потерянные на карте «Лабиринт», могут быть возвращены страховкой.", "fr-FR": "Une fois activé, les objets perdus sur The Labyrinth peuvent être rendus par l'assurance.", "jp-JP": "有効にすると、The Labyrinthで失ったアイテムが保険で返還される可能性があります。"},
    "Develop.Desc.UnloadSpeed": {"zh-CN": "调整武器装卸（弹匣/弹药）速度倍率。", "en-US": "Adjusts the weapon reload speed multiplier (magazines and ammo).", "ru-RU": "Регулирует скорость перезарядки оружия (магазины и патроны).", "fr-FR": "Règle le multiplicateur de vitesse de rechargement des armes (chargeurs et munitions).", "jp-JP": "武器のリロード（マガジン・弾薬）速度倍率を調整します。"},
    "Develop.Desc.SkillExpBoost": {"zh-CN": "提升所有技能的经验获取倍率，升级更快。", "en-US": "Boosts experience gain for all skills; leveling up becomes faster.", "ru-RU": "Увеличивает получение опыта всех навыков; прокачка быстрее.", "fr-FR": "Augmente le gain d'expérience de toutes les compétences ; la progression est plus rapide.", "jp-JP": "全スキルの経験値獲得倍率を向上させ、成長を速めます。"},
    "Develop.Desc.SupermanMode": {"zh-CN": "大幅强化角色能力（体力、负重、跳跃、速度等），体验超人效果。", "en-US": "Greatly boosts character abilities (stamina, carry weight, jump, speed, etc.) for a superhuman feel.", "ru-RU": "Сильно усиливает способности персонажа (выносливость, вес, прыжок, скорость) в стиле супермена.", "fr-FR": "Renforce fortement les capacités du personnage (endurance, charge, saut, vitesse) pour un effet surhumain.", "jp-JP": "キャラクター能力（スタミナ・持ち運び重量・ジャンプ・速度など）を大幅強化し、超人体験を提供します。"},
    "Develop.Desc.NoCarryLimit": {"zh-CN": "移除负重上限与超重惩罚。", "en-US": "Removes the carry weight limit and over-encumbrance penalties.", "ru-RU": "Убирает лимит переносимого веса и штрафы за перегруз.", "fr-FR": "Supprime la limite de charge et les pénalités de surcharge.", "jp-JP": "持ち運び重量の上限と過積載のペナルティを撤廃します。"},
    "Develop.Desc.WeaponSlotCompat": {"zh-CN": "放宽武器配件安装限制，任意配件可装任意武器。", "en-US": "Relaxes weapon attachment restrictions; any attachment fits any weapon.", "ru-RU": "Ослабляет ограничения на установку модулей; любой модуль ставится на любое оружие.", "fr-FR": "Assouplit les restrictions d'installation des accessoires ; tout accessoire s'adapte à toute arme.", "jp-JP": "武器アタッチメントの装着制限を緩和し、どのアタッチメントもどの武器に装着可能にします。"},
    "Develop.Desc.WeaponNoJam": {"zh-CN": "关闭武器故障机制，射击不再随机卡壳。", "en-US": "Disables weapon malfunction; firearms no longer jam randomly.", "ru-RU": "Отключает осечки; оружие больше не заклинивает случайно.", "fr-FR": "Désactive les pannes d'arme ; les armes ne s'enrayent plus aléatoirement.", "jp-JP": "武器の故障機構を無効化します。射撃中にランダムにジャムしなくなります。"},
    "Develop.Desc.WeaponNoDurabilityLoss": {"zh-CN": "武器使用不消耗耐久度。", "en-US": "Weapons no longer lose durability from use.", "ru-RU": "Оружие больше не теряет прочность при использовании.", "fr-FR": "Les armes ne perdent plus de durabilité à l'usage.", "jp-JP": "武器の使用で耐久度が減らなくなります。"},
    "Develop.Desc.MagazineCapacity": {"zh-CN": "调整所有弹匣的容量倍率。", "en-US": "Adjusts the capacity multiplier of all magazines.", "ru-RU": "Регулирует множитель вместимости всех магазинов.", "fr-FR": "Règle le multiplicateur de capacité de tous les chargeurs.", "jp-JP": "全マガジンの容量倍率を調整します。"},
    "Develop.Desc.HelmetHeadsetCompat": {"zh-CN": "允许头盔与头戴式装备（耳机等）同时佩戴。", "en-US": "Allows helmets and headwear (headsets, etc.) to be worn together.", "ru-RU": "Позволяет носить шлем вместе с головными устройствами (наушниками и т.д.).", "fr-FR": "Permet de porter un casque avec un équipement de tête (casque audio, etc.).", "jp-JP": "ヘルメットとヘッドセットなどの頭部装備を同時に装着できます。"},
    "Develop.Desc.HelmetNoDebuff": {"zh-CN": "佩戴头盔不再有听觉、视野等负面效果。", "en-US": "Helmets no longer impose hearing, vision, or other debuffs.", "ru-RU": "Шлемы больше не дают негативных эффектов (слух, обзор и т.д.).", "fr-FR": "Les casques n'imposent plus de malus (audition, champ de vision, etc.).", "jp-JP": "ヘルメットの聴覚・視界などのデバフがなくなります。"},
    "Develop.Desc.HelmetNoWeight": {"zh-CN": "头盔不再占用负重。", "en-US": "Helmets no longer contribute to carry weight.", "ru-RU": "Шлемы больше не добавляют вес.", "fr-FR": "Les casques ne pèsent plus dans la charge.", "jp-JP": "ヘルメットが重量に影響しなくなります。"},
    "Develop.Desc.RigArmorCompat": {"zh-CN": "允许护甲与弹挂同时穿戴，互不冲突。", "en-US": "Allows armor and rigs to be worn together without conflict.", "ru-RU": "Позволяет носить броню и разгрузку одновременно без конфликтов.", "fr-FR": "Permet de porter une armure et un rig ensemble sans conflit.", "jp-JP": "アーマーとリグを同時に装着でき、競合しなくなります。"},
    "Develop.Desc.RigArmorNoDebuff": {"zh-CN": "穿戴护甲弹挂不再有移动、体力等负面效果。", "en-US": "Armor and rigs no longer impose movement or stamina debuffs.", "ru-RU": "Броня и разгрузки больше не дают штрафов к движению и выносливости.", "fr-FR": "Les armures et rigs n'imposent plus de malus de mouvement ou d'endurance.", "jp-JP": "アーマー・リグの移動・スタミナへのデバフがなくなります。"},
    "Develop.Desc.RigArmorNoWeight": {"zh-CN": "护甲与弹挂不占用负重。", "en-US": "Armor and rigs no longer contribute to carry weight.", "ru-RU": "Броня и разгрузки больше не добавляют вес.", "fr-FR": "Les armures et rigs ne pèsent plus dans la charge.", "jp-JP": "アーマーとリグが重量に影響しなくなります。"},
    "Develop.Desc.RigArmorNoDurabilityLoss": {"zh-CN": "护甲与弹挂不消耗耐久。", "en-US": "Armor and rigs no longer lose durability.", "ru-RU": "Броня и разгрузки больше не теряют прочность.", "fr-FR": "Les armures et rigs ne perdent plus de durabilité.", "jp-JP": "アーマーとリグの耐久度が減らなくなります。"},
    "Develop.Desc.PlateCarrierDurability": {"zh-CN": "调整防弹插板与内衬的耐久倍率。", "en-US": "Adjusts the durability multiplier of armor plates and liners.", "ru-RU": "Регулирует множитель прочности бронепластин и подкладок.", "fr-FR": "Règle le multiplicateur de durabilité des plaques et doublures balistiques.", "jp-JP": "防弾プレートとライナーの耐久倍率を調整します。"},
    "Develop.Desc.PlateCarrierNoDebuff": {"zh-CN": "穿插板胸挂不再有行动惩罚。", "en-US": "Plate carriers no longer impose movement penalties.", "ru-RU": "Бронежилеты с пластинами больше не дают штрафов к движению.", "fr-FR": "Les plaques porteuses n'imposent plus de pénalités de mouvement.", "jp-JP": "プレートキャリアの行動ペナルティがなくなります。"},
    "Develop.Desc.PlateCarrierNoWeight": {"zh-CN": "插板胸挂不占用负重。", "en-US": "Plate carriers no longer contribute to carry weight.", "ru-RU": "Бронежилеты с пластинами больше не добавляют вес.", "fr-FR": "Les plaques porteuses ne pèsent plus dans la charge.", "jp-JP": "プレートキャリアが重量に影響しなくなります。"},
    "Develop.Desc.BackpackCompat": {"zh-CN": "允许任意背包相互嵌套（包中包）。", "en-US": "Allows backpacks to be nested inside each other (bag-in-bag).", "ru-RU": "Позволяет вкладывать рюкзаки друг в друга (рюкзак в рюкзак).", "fr-FR": "Permet d'imbriquer les sacs les uns dans les autres (sac dans le sac).", "jp-JP": "バックパック同士を入れ子にできます（バッグインバッグ）。"},
    "Develop.Desc.BackpackCompact": {"zh-CN": "背包内物品占用体积缩小，可装载更多。", "en-US": "Items inside backpacks take less space, allowing more to be carried.", "ru-RU": "Предметы в рюкзаках занимают меньше места, помещается больше.", "fr-FR": "Les objets dans les sacs prennent moins de place, on peut en emporter plus.", "jp-JP": "バックパック内のアイテムの占有容量が小さくなり、より多く収納できます。"},
    "Develop.Desc.BackpackNoDebuff": {"zh-CN": "背包不再影响移动速度等属性。", "en-US": "Backpacks no longer affect movement speed or other attributes.", "ru-RU": "Рюкзаки больше не влияют на скорость движения и другие параметры.", "fr-FR": "Les sacs n'affectent plus la vitesse de déplacement ni d'autres attributs.", "jp-JP": "バックパックが移動速度などのステータスに影響しなくなります。"},
    "Develop.Desc.BackpackNoWeight": {"zh-CN": "背包及其内物品不计负重。", "en-US": "Backpacks and their contents no longer count toward carry weight.", "ru-RU": "Рюкзаки и их содержимое больше не учитываются в весе.", "fr-FR": "Les sacs et leur contenu ne comptent plus dans la charge.", "jp-JP": "バックパックと中身が重量に影響しなくなります。"},
    "Develop.Desc.WeaponEnchant100": {"zh-CN": "武器基础属性强化至满（精准、人机工效等 100%）。", "en-US": "Maxes out base weapon stats (accuracy, ergonomics, etc.).", "ru-RU": "Усиливает базовые характеристики оружия до максимума (точность, эргономика и т.д.).", "fr-FR": "Maximise les statistiques de base des armes (précision, ergonomie, etc.).", "jp-JP": "武器の基礎ステータス（精度・人間工学など）を最大まで強化します。"},
    "Develop.Desc.ArmorEnchant100": {"zh-CN": "护甲防护属性强化至满。", "en-US": "Maxes out armor protection stats.", "ru-RU": "Усиливает защитные характеристики брони до максимума.", "fr-FR": "Maximise les statistiques de protection des armures.", "jp-JP": "アーマーの防御ステータスを最大まで強化します。"},
    "Develop.Desc.InsuranceExpand": {"zh-CN": "安全箱格子扩容。", "en-US": "Expands the grid of secure containers.", "ru-RU": "Расширяет сетку защищённых контейнеров.", "fr-FR": "Agrandit la grille des conteneurs sécurisés.", "jp-JP": "セキュアコンテナのグリッドを拡張します。"},
    "Develop.Desc.InsuranceCompat": {"zh-CN": "安全箱可存放更多类别的物品。", "en-US": "Secure containers can hold more categories of items.", "ru-RU": "Сейфы могут хранить больше категорий предметов.", "fr-FR": "Les conteneurs sécurisés peuvent contenir plus de catégories d'objets.", "jp-JP": "セキュアコンテナに収納できるアイテムのカテゴリが拡大します。"},
    "Develop.Desc.InsuranceNoWeight": {"zh-CN": "安全箱内物品不计负重。", "en-US": "Items inside secure containers no longer count toward carry weight.", "ru-RU": "Предметы в сейфах больше не учитываются в весе.", "fr-FR": "Les objets dans les conteneurs sécurisés ne comptent plus dans la charge.", "jp-JP": "セキュアコンテナ内のアイテムが重量に影響しなくなります。"},
    "Develop.Desc.T7ThermalBoost": {"zh-CN": "强化 T7 热成像目镜及同类热成像装备的显示与探测能力。", "en-US": "Enhances the display and detection performance of T-7 Thermal Goggles and similar thermal optics.", "ru-RU": "Усиливает отображение и обнаружение тепловизионных очков T-7 и аналогичных приборов.", "fr-FR": "Améliore l'affichage et la détection des lunettes thermiques T-7 et des optiques similaires.", "jp-JP": "T-7サーマルゴーグルなどの熱成像機器の表示と探知能力を強化します。"},
    "Develop.Desc.KeyUnlimitedDurability": {"zh-CN": "钥匙使用不再消耗耐久。", "en-US": "Keys no longer lose durability from use.", "ru-RU": "Ключи больше не теряют прочность при использовании.", "fr-FR": "Les clés ne perdent plus de durabilité à l'usage.", "jp-JP": "鍵の使用で耐久度が減らなくなります。"},
    "Develop.Desc.MedicalItemDurability": {"zh-CN": "调整医疗物品的使用次数/耐久。", "en-US": "Adjusts the durability or use count of medical items.", "ru-RU": "Регулирует прочность/количество использований медикаментов.", "fr-FR": "Règle la durabilité ou le nombre d'utilisations des objets médicaux.", "jp-JP": "医療アイテムの使用回数/耐久度を調整します。"},
    "Develop.Desc.AmmoStack": {"zh-CN": "调整弹药每组可堆叠数量。", "en-US": "Adjusts the stack size of ammunition.", "ru-RU": "Регулирует размер стака патронов.", "fr-FR": "Règle la taille de pile des munitions.", "jp-JP": "弾薬のスタック数を調整します。"},
    "Develop.Desc.MoneyStack": {"zh-CN": "调整货币每组堆叠数量。", "en-US": "Adjusts the stack size of money.", "ru-RU": "Регулирует размер стака денег.", "fr-FR": "Règle la taille de pile de l'argent.", "jp-JP": "通貨のスタック数を調整します。"},
    "Develop.Desc.FullInspect": {"zh-CN": "所有物品无需鉴定即可查看属性（免除“未检视”状态）。", "en-US": "All items can be fully inspected without identification (no more “unexamined” state).", "ru-RU": "Все предметы можно полностью осмотреть без идентификации (нет статуса «не осмотрен»).", "fr-FR": "Tous les objets peuvent être inspectés sans identification (fini l'état « non examiné »).", "jp-JP": "鑑定なしですべてのアイテムを検査できます（「未検査」状態がなくなります）。"},
    "Develop.Desc.QuestFreeReset": {"zh-CN": "任务重置不再消耗费用。", "en-US": "Quest resets no longer cost anything.", "ru-RU": "Сброс заданий больше не требует оплаты.", "fr-FR": "La réinitialisation des quêtes ne coûte plus rien.", "jp-JP": "クエストのリセットが無料になります。"},
    "Develop.Desc.QuestOptimize": {"zh-CN": "简化任务条件，降低任务难度。", "en-US": "Simplifies quest conditions and lowers quest difficulty.", "ru-RU": "Упрощает условия заданий и снижает их сложность.", "fr-FR": "Simplifie les conditions des quêtes et réduit leur difficulté.", "jp-JP": "クエスト条件を簡略化し、難易度を下げます。"},
    "Develop.Desc.Quest3X4Marker": {"zh-CN": "修正/简化 3X4 任务链（收藏家）的标记条件。", "en-US": "Fixes/simplifies the marking conditions of the 3X4 (Collector) quest chain.", "ru-RU": "Исправляет/упрощает условия маркировки цепочки заданий 3X4 (Коллекционер).", "fr-FR": "Corrige/simplifie les conditions de marquage de la chaîne de quêtes 3X4 (Collectionneur).", "jp-JP": "3X4クエストチェーン（コレクター）のマーキング条件を修正・簡略化します。"},
    "Develop.Desc.HideoutUpgradeTime": {"zh-CN": "调整藏身处设施升级所需时间。", "en-US": "Adjusts the time required to upgrade hideout facilities.", "ru-RU": "Регулирует время улучшения сооружений убежища.", "fr-FR": "Règle le temps nécessaire pour améliorer les installations de la planque.", "jp-JP": "Hideoutの施設アップグレードにかかる時間を調整します。"},
    "Develop.Desc.HideoutProductionTime": {"zh-CN": "调整藏身处生产（制作）所需时间。", "en-US": "Adjusts the time required for hideout production (crafting).", "ru-RU": "Регулирует время производства (крафта) в убежище.", "fr-FR": "Règle le temps de production (artisanat) de la planque.", "jp-JP": "Hideoutでの生産（クラフト）にかかる時間を調整します。"},
    "Develop.Desc.ScavCaseTime": {"zh-CN": "调整 Scav 宝箱（幸运Scav垃圾箱）的工作周期。", "en-US": "Adjusts the cycle time of the Scav case (Lucky Scav Junk box).", "ru-RU": "Регулирует цикл работы кейса для хлама.", "fr-FR": "Règle le cycle de la boite Lucky Scav.", "jp-JP": "Scavケース（Lucky Scav ジャンクボックス）の稼働サイクルを調整します。"},
    "Develop.Desc.HideoutUpgradeUnlimited": {"zh-CN": "藏身处升级不再受等级、物资与前置设施限制。", "en-US": "Hideout upgrades are no longer limited by level, materials, or prerequisite facilities.", "ru-RU": "Улучшение убежища больше не ограничено уровнем, материалами и предварительными сооружениями.", "fr-FR": "Les améliorations de la planque ne sont plus limitées par le niveau, les matériaux ou les prérequis.", "jp-JP": "Hideoutのアップグレードがレベル・素材・前提施設の制限を受けなくなります。"},
    "Develop.Desc.HideoutAreaBonusLevel": {"zh-CN": "调整藏身处设施提供的技能加成等级。", "en-US": "Adjusts the skill bonus level granted by hideout facilities.", "ru-RU": "Регулирует уровень бонуса навыков от сооружений убежища.", "fr-FR": "Règle le niveau de bonus de compétences accordé par les installations de la planque.", "jp-JP": "Hideoutの施設が与えるスキルボーナスのレベルを調整します。"},
    "Develop.Desc.HideoutNoPower": {"zh-CN": "藏身处区域不再需要供电，燃料不再是前置条件。", "en-US": "Hideout areas no longer need power; fuel is no longer a requirement.", "ru-RU": "Районы убежища больше не требуют электроэнергии; топливо больше не обязательно.", "fr-FR": "Les zones de la planque n'ont plus besoin d'électricité ; le carburant n'est plus requis.", "jp-JP": "Hideoutエリアが電力を必要としなくなり、燃料も不要になります。"},
    "Develop.Desc.GymAlwaysSucceed": {"zh-CN": "健身区锻炼必定成功。", "en-US": "Gym workouts always succeed.", "ru-RU": "Тренировки в тренажёрном зале всегда успешны.", "fr-FR": "Les entraînements au coin sport réussissent toujours.", "jp-JP": "ジムのトレーニングが必ず成功します。"},
    "Develop.Desc.GymNoPenalty": {"zh-CN": "健身区锻炼失败不再有惩罚。", "en-US": "Failed gym workouts no longer impose penalties.", "ru-RU": "Проваленные тренировки в тренажёрном зале больше не дают штрафов.", "fr-FR": "Les entraînements ratés au coin sport n'imposent plus de pénalités.", "jp-JP": "ジムのトレーニング失敗時のペナルティがなくなります。"},
    "Develop.Desc.GymRewardMultiplier": {"zh-CN": "调整健身区锻炼获得的属性奖励倍率。", "en-US": "Adjusts the attribute reward multiplier from gym workouts.", "ru-RU": "Регулирует множитель наград за тренировки в тренажёрном зале.", "fr-FR": "Règle le multiplicateur de récompenses d'attributs des entraînements au coin sport.", "jp-JP": "ジムのトレーニングで得られるステータス報酬の倍率を調整します。"},
    "Economy.Desc.FleaTradeMultiplier": {"zh-CN": "调整跳蚤市场交易（挂单/购买）倍数。", "en-US": "Adjusts the Flea Market trade multiplier (listings/purchases).", "ru-RU": "Регулирует множитель сделок на барахолке (лоты/покупки).", "fr-FR": "Règle le multiplicateur de transactions du marché aux puces (offres/achats).", "jp-JP": "フリーマーケットの取引（出品/購入）倍率を調整します。"},
    "Economy.Desc.FleaSell100": {"zh-CN": "挂在跳蚤市场的物品必定售出。", "en-US": "Items listed on the Flea Market always sell.", "ru-RU": "Предметы на барахолке продаются всегда.", "fr-FR": "Les objets mis en vente sur le marché aux puces se vendent toujours.", "jp-JP": "フリーマーケットに出品したアイテムは必ず売れます。"},
    "Economy.Desc.FleaInstantSell": {"zh-CN": "挂单立即售出，无需等待买家。", "en-US": "Listings sell instantly without waiting for a buyer.", "ru-RU": "Лоты продаются мгновенно, без ожидания покупателя.", "fr-FR": "Les offres se vendent instantanément, sans attendre d'acheteur.", "jp-JP": "出品が即座に売れ、購入者を待つ必要がなくなります。"},
    "Economy.Desc.FleaBuyBoost": {"zh-CN": "优化跳蚤市场的购买体验（刷新与库存）。", "en-US": "Optimizes the Flea Market buying experience (refresh and stock).", "ru-RU": "Оптимизирует опыт покупок на барахолке (обновление и наличие).", "fr-FR": "Optimise l'expérience d'achat du marché aux puces (rafraîchissement et stock).", "jp-JP": "フリーマーケットの購入体験（更新・在庫）を最適化します。"},
    "Economy.Desc.FleaBrandNew": {"zh-CN": "跳蚤市场出售的物品均为全新状态。", "en-US": "Items sold on the Flea Market are always in brand-new condition.", "ru-RU": "Предметы на барахолке всегда продаются в новом состоянии.", "fr-FR": "Les objets vendus sur le marché aux puces sont toujours en parfait état.", "jp-JP": "フリーマーケットで販売されるアイテムは常に新品状態です。"},
    "Economy.Desc.FleaDisableBlacklist": {"zh-CN": "移除跳蚤市场物品上架黑名单，全部物品可挂。", "en-US": "Removes the Flea Market listing blacklist; all items can be listed.", "ru-RU": "Убирает чёрный список барахолки; можно выставлять любые предметы.", "fr-FR": "Supprime la liste noire du marché aux puces ; tous les objets peuvent être mis en vente.", "jp-JP": "フリーマーケットの出品ブラックリストを撤廃し、全アイテムを出品可能にします。"},
    "Economy.Desc.FleaOpenLevel": {"zh-CN": "移除跳蚤市场的等级解锁限制，开局即可使用。", "en-US": "Removes the level requirement for the Flea Market; available from the start.", "ru-RU": "Убирает ограничение по уровню для барахолки; доступна с самого начала.", "fr-FR": "Supprime le niveau requis pour le marché aux puces ; disponible dès le début.", "jp-JP": "フリーマーケットのレベル制限を撤廃し、最初から利用可能にします。"},
    "Economy.Desc.LowTax": {"zh-CN": "大幅降低跳蚤市场交易税率。", "en-US": "Greatly reduces the Flea Market transaction tax.", "ru-RU": "Сильно снижает налог на сделки барахолки.", "fr-FR": "Réduit fortement la taxe de transaction du marché aux puces.", "jp-JP": "フリーマーケットの取引税率を大幅に引き下げます。"},
    "Economy.Desc.TraderSupplyTime": {"zh-CN": "调整商人库存刷新周期。", "en-US": "Adjusts the trader restock interval.", "ru-RU": "Регулирует период обновления запасов торговцев.", "fr-FR": "Règle l'intervalle de réapprovisionnement des marchands.", "jp-JP": "商人の在庫更新周期を調整します。"},
    "Economy.Desc.InsuranceReturnSpeed": {"zh-CN": "调整保险物品返还所需时间。", "en-US": "Adjusts how long insurance returns take.", "ru-RU": "Регулирует время возврата застрахованных предметов.", "fr-FR": "Règle le délai de retour des objets assurés.", "jp-JP": "保険返還にかかる時間を調整します。"},
    "Economy.Desc.InsuranceCost": {"zh-CN": "调整投保费用。", "en-US": "Adjusts insurance cost.", "ru-RU": "Регулирует стоимость страховки.", "fr-FR": "Règle le coût de l'assurance.", "jp-JP": "保険料を調整します。"},
    "Economy.Desc.InsuranceReturnChance": {"zh-CN": "调整保险返还成功率。", "en-US": "Adjusts the insurance return success chance.", "ru-RU": "Регулирует вероятность возврата страховки.", "fr-FR": "Règle la probabilité de retour de l'assurance.", "jp-JP": "保険返還の成功率を調整します。"},
    "Economy.Desc.BuyWithHook": {"zh-CN": "允许购买带“战利品”标记（钩）的物品。", "en-US": "Allows buying items marked as found-in-raid (with the “hook”).", "ru-RU": "Позволяет покупать предметы с пометкой «найдено в рейде».", "fr-FR": "Permet d'acheter des objets marqués comme trouvés en raid.", "jp-JP": "「レイド内で見つけた」マーク付きアイテムを購入できるようにします。"},
    "Feature.Desc.IndependentTrader": {"zh-CN": "启用 MG-Mod 自带独立商人（麻瓜与 FG），与官方商人并存。", "en-US": "Enables MG-Mod's independent traders (Muggle and FG), coexisting with official traders.", "ru-RU": "Включает собственных торговцев MG-Mod (Мугл и FG), сосуществующих с официальными.", "fr-FR": "Active les marchands indépendants de MG-Mod (Muggle et FG), coexistants avec les marchands officiels.", "jp-JP": "MG-Mod独自の独立商人（マグル＆FG）を有効にします。公式商人と共存します。"},
    "Feature.Desc.IndependentItem": {"zh-CN": "启用 MG-Mod 自定义物品（护甲、弹挂、钥匙等）。", "en-US": "Enables MG-Mod custom items (armor, rigs, keys, etc.).", "ru-RU": "Включает кастомные предметы MG-Mod (броня, разгрузки, ключи и т.д.).", "fr-FR": "Active les objets personnalisés de MG-Mod (armures, rigs, clés, etc.).", "jp-JP": "MG-Modのカスタムアイテム（アーマー・リグ・鍵など）を有効にします。"},
    "Feature.Desc.IndependentPreset": {"zh-CN": "启用 MG-Mod 自定义装备预设。", "en-US": "Enables MG-Mod custom equipment presets.", "ru-RU": "Включает кастомные пресеты снаряжения MG-Mod.", "fr-FR": "Active les préréglages d'équipement personnalisés de MG-Mod.", "jp-JP": "MG-Modのカスタム装備プリセットを有効にします。"},
    "Feature.Desc.IndependentSave": {"zh-CN": "启用 MG-Mod 独立存档与配置管理。", "en-US": "Enables MG-Mod independent profile and config management.", "ru-RU": "Включает независимое управление профилем и конфигурацией MG-Mod.", "fr-FR": "Active la gestion indépendante du profil et de la configuration de MG-Mod.", "jp-JP": "MG-Modの独立したプロフィール・設定管理を有効にします。"},
    "Feature.Desc.BulletData": {"zh-CN": "在游戏内显示子弹的详细数据（穿透、伤害等）。", "en-US": "Displays detailed bullet data in game (penetration, damage, etc.).", "ru-RU": "Показывает подробные данные патронов в игре (пробитие, урон и т.д.).", "fr-FR": "Affiche les données détaillées des munitions en jeu (pénétration, dégâts, etc.).", "jp-JP": "ゲーム内で弾丸の詳細データ（貫通・ダメージなど）を表示します。"},
    "Feature.Desc.KeyCategory": {"zh-CN": "按地图对钥匙进行分类整理。", "en-US": "Organizes keys by map category.", "ru-RU": "Сортирует ключи по картам.", "fr-FR": "Organise les clés par carte.", "jp-JP": "鍵をマップごとに分類整理します。"},
    "Feature.Desc.RealTimeFlea": {"zh-CN": "跳蚤市场数据实时同步与刷新。", "en-US": "Flea market data updates and refreshes in real time.", "ru-RU": "Данные барахолки обновляются в реальном времени.", "fr-FR": "Les données du marché aux puces se synchronisent et se rafraîchissent en temps réel.", "jp-JP": "フリーマーケットのデータをリアルタイムで同期・更新します。"},
    "Container.Desc.Enable": {"zh-CN": "开启该容器的格子扩容，按下方宽度/高度设置调整容量。", "en-US": "Enables grid expansion for this container, resizing it per the width/height settings below.", "ru-RU": "Включает расширение сетки этого контейнера в соответствии с настройками ширины/высоты ниже.", "fr-FR": "Active l'agrandissement de la grille de ce conteneur, selon les réglages de largeur/hauteur ci-dessous.", "jp-JP": "このコンテナのグリッド拡張を有効にします。下の幅/高さ設定に従って容量が変わります。"},
    "Container.Desc.Width": {"zh-CN": "设置该容器扩容后的格子宽度。", "en-US": "Sets the grid width of this container after expansion.", "ru-RU": "Задаёт ширину сетки контейнера после расширения.", "fr-FR": "Définit la largeur de la grille de ce conteneur après agrandissement.", "jp-JP": "拡張後のこのコンテナのグリッド幅を設定します。"},
    "Container.Desc.Height": {"zh-CN": "设置该容器扩容后的格子高度。", "en-US": "Sets the grid height of this container after expansion.", "ru-RU": "Задаёт высоту сетки контейнера после расширения.", "fr-FR": "Définit la hauteur de la grille de ce conteneur après agrandissement.", "jp-JP": "拡張後のこのコンテナのグリッド高さを設定します。"},
    "Container.Desc.Compatible": {"zh-CN": "允许该容器存放更多类别的物品。", "en-US": "Allows this container to hold more categories of items.", "ru-RU": "Позволяет контейнеру хранить больше категорий предметов.", "fr-FR": "Permet à ce conteneur de contenir plus de catégories d'objets.", "jp-JP": "このコンテナに収納できるアイテムのカテゴリを拡大します。"},
    "Container.Desc.NoWeight": {"zh-CN": "该容器内物品不计负重。", "en-US": "Items inside this container no longer count toward carry weight.", "ru-RU": "Предметы в этом контейнере больше не учитываются в весе.", "fr-FR": "Les objets dans ce conteneur ne comptent plus dans la charge.", "jp-JP": "このコンテナ内のアイテムが重量に影響しなくなります。"},
    "Raid.HeaderDesc.AI": {"zh-CN": "AI 相关设置：血量、刷新数量、阵营比例、名字池与 PMC 行为。", "en-US": "AI settings: health, spawn numbers, faction ratios, name pool, and PMC behavior.", "ru-RU": "Настройки AI: здоровье, количество спавна, соотношение фракций, имена и поведение PMC.", "fr-FR": "Réglages IA : santé, apparitions, ratios de factions, noms et comportement des PMC.", "jp-JP": "AI関連の設定：体力、出現数、陣営比率、名前プール、PMCの行動。"},
    "Raid.HeaderDesc.DefaultOptions": {"zh-CN": "自定义战局默认的 AI 数量、难度、BOSS 与 SCAV 行为。", "en-US": "Customizes default raid options: AI amount, difficulty, bosses, and Scav behavior.", "ru-RU": "Настройка параметров рейда по умолчанию: количество AI, сложность, боссы и поведение Scav.", "fr-FR": "Personnalise les options de raid par défaut : nombre d'IA, difficulté, boss et comportement des Scavs.", "jp-JP": "レイドのデフォルト設定をカスタマイズ：AI数、難易度、ボス、Scavの行動。"},
    "Raid.HeaderDesc.Raid": {"zh-CN": "战局时长、BOSS 刷新、空投、撤离与 SCAV 相关设置。", "en-US": "Raid duration, boss spawns, airdrops, extracts, and Scav settings.", "ru-RU": "Длительность рейда, спавн боссов, аирдропы, выходы и настройки Scav.", "fr-FR": "Durée du raid, apparitions de boss, largages, sorties et réglages Scav.", "jp-JP": "レイド時間、ボス出現、エアドロップ、脱出、Scav関連の設定。"},
    "Raid.HeaderDesc.Weather": {"zh-CN": "战局天气表现：全局模式、云量、风、雨与雾。", "en-US": "Raid weather: global mode, clouds, wind, rain, and fog.", "ru-RU": "Погода в рейде: глобальный режим, облачность, ветер, дождь и туман.", "fr-FR": "Météo des raids : mode global, nuages, vent, pluie et brouillard.", "jp-JP": "レイドの天候：グローバルモード、雲量、風、雨、霧。"},
    "Raid.HeaderDesc.Resources": {"zh-CN": "全局与分地图的战利品刷新倍率。", "en-US": "Global and per-map loot spawn multipliers.", "ru-RU": "Множители спавна лута глобально и по картам.", "fr-FR": "Multiplicateurs d'apparition du butin, globaux et par carte.", "jp-JP": "全体・マップ別の戦利品出現倍率。"},
    "Raid.HeaderDesc.MapInsurance": {"zh-CN": "按地图开关物品的保险返还。", "en-US": "Toggles insurance returns per map.", "ru-RU": "Включение страхового возврата предметов по картам.", "fr-FR": "Active le retour d'assurance des objets par carte.", "jp-JP": "マップごとの保険返却のオン/オフ。"},
    "Develop.HeaderDesc.BaseAttributes": {"zh-CN": "角色基础能力：装卸速度、技能经验、负重限制等。", "en-US": "Basic character stats: reload speed, skill experience, carry limits, etc.", "ru-RU": "Базовые параметры персонажа: скорость перезарядки, опыт навыков, лимиты веса и т.д.", "fr-FR": "Capacités de base du personnage : rechargement, expérience de compétence, limites de charge, etc.", "jp-JP": "キャラクターの基礎能力：リロード速度、スキル経験値、重量制限など。"},
    "Develop.HeaderDesc.WeaponOpt": {"zh-CN": "武器相关：配件兼容、故障、耐久与弹匣容量。", "en-US": "Weapon settings: attachment compatibility, malfunctions, durability, and magazine capacity.", "ru-RU": "Настройки оружия: совместимость модулей, осечки, прочность и вместимость магазинов.", "fr-FR": "Réglages d'armes : compatibilité des accessoires, pannes, durabilité et capacité des chargeurs.", "jp-JP": "武器関連：アタッチメント互換、故障、耐久度、マガジン容量。"},
    "Develop.HeaderDesc.HelmetOpt": {"zh-CN": "头盔的兼容性、负面效果与负重。", "en-US": "Helmet compatibility, debuffs, and weight.", "ru-RU": "Шлемы: совместимость, негативные эффекты и вес.", "fr-FR": "Casques : compatibilité, malus et poids.", "jp-JP": "ヘルメットの互換性、デバフ、重量。"},
    "Develop.HeaderDesc.RigArmorOpt": {"zh-CN": "护甲与弹挂的兼容性、负面效果、负重与耐久。", "en-US": "Armor and rigs: compatibility, debuffs, weight, and durability.", "ru-RU": "Броня и разгрузки: совместимость, негативные эффекты, вес и прочность.", "fr-FR": "Armures et rigs : compatibilité, malus, poids et durabilité.", "jp-JP": "アーマーとリグの互換性、デバフ、重量、耐久度。"},
    "Develop.HeaderDesc.PlateCarrierOpt": {"zh-CN": "防弹插板与内衬的耐久、行动惩罚与负重。", "en-US": "Armor plates and liners: durability, movement penalties, and weight.", "ru-RU": "Бронепластины и подкладки: прочность, штрафы к движению и вес.", "fr-FR": "Plaques et doublures balistiques : durabilité, pénalités de mouvement et poids.", "jp-JP": "防弾プレートとライナーの耐久度、行動ペナルティ、重量。"},
    "Develop.HeaderDesc.BackpackOpt": {"zh-CN": "背包的嵌套、体积、负面效果与负重。", "en-US": "Backpacks: nesting, size, debuffs, and weight.", "ru-RU": "Рюкзаки: вложение, размер, негативные эффекты и вес.", "fr-FR": "Sacs à dos : imbrication, taille, malus et poids.", "jp-JP": "バックパックの入れ子、サイズ、デバフ、重量。"},
    "Develop.HeaderDesc.EnchantOpt": {"zh-CN": "武器与护甲的基础属性强化。", "en-US": "Base stat enhancements for weapons and armor.", "ru-RU": "Усиление базовых характеристик оружия и брони.", "fr-FR": "Renforcement des statistiques de base des armes et armures.", "jp-JP": "武器とアーマーの基礎ステータス強化。"},
    "Develop.HeaderDesc.InsuranceOpt": {"zh-CN": "安全箱（保险箱）的扩容、兼容与负重。", "en-US": "Secure containers: expansion, item compatibility, and weight.", "ru-RU": "Защищённые контейнеры: расширение, совместимость предметов и вес.", "fr-FR": "Conteneurs sécurisés : agrandissement, compatibilité d'objets et poids.", "jp-JP": "セキュアコンテナの拡張、収納互換、重量。"},
    "Develop.HeaderDesc.ItemAttrOpt": {"zh-CN": "热成像、钥匙与医疗物品的属性调整。", "en-US": "Item attributes: thermals, keys, and medical items.", "ru-RU": "Свойства предметов: тепловизоры, ключи и медикаменты.", "fr-FR": "Attributs d'objets : thermiques, clés et objets médicaux.", "jp-JP": "アイテム属性：熱成像、鍵、医療アイテム。"},
    "Develop.HeaderDesc.WarehouseOpt": {"zh-CN": "弹药与货币的堆叠数量、物品全检视。", "en-US": "Ammo and money stack sizes, and full item inspection.", "ru-RU": "Размер стака патронов и денег, полный осмотр предметов.", "fr-FR": "Tailles de pile des munitions et de l'argent, inspection complète.", "jp-JP": "弾薬・通貨のスタック数、全アイテム検査。"},
    "Develop.HeaderDesc.QuestSystem": {"zh-CN": "任务重置、条件简化与 3X4 任务链。", "en-US": "Quest resets, simplified conditions, and the 3X4 quest chain.", "ru-RU": "Сброс заданий, упрощение условий и цепочка заданий 3X4.", "fr-FR": "Réinitialisation des quêtes, conditions simplifiées et chaîne 3X4.", "jp-JP": "クエストのリセット、条件簡略化、3X4クエストチェーン。"},
    "Develop.HeaderDesc.Hideout": {"zh-CN": "藏身处升级、生产、供电与健身房相关。", "en-US": "Hideout upgrades, production, power, and the gym.", "ru-RU": "Улучшение убежища, производство, энергопитание и спортзал.", "fr-FR": "Améliorations de la planque, production, électricité et coin sport.", "jp-JP": "Hideoutのアップグレード、生産、電力、ジム。"},
    "Economy.HeaderDesc.Flea": {"zh-CN": "跳蚤市场的交易、出售、购买与税率设置。", "en-US": "Flea Market trading, selling, buying, and tax settings.", "ru-RU": "Настройки барахолки: сделки, продажа, покупка и налоги.", "fr-FR": "Marché aux puces : transactions, ventes, achats et taxes.", "jp-JP": "フリーマーケットの取引、販売、購入、税率の設定。"},
    "Economy.HeaderDesc.Trader": {"zh-CN": "商人供货周期与保险相关设置。", "en-US": "Trader restock intervals and insurance settings.", "ru-RU": "Период обновления запасов торговцев и настройки страховки.", "fr-FR": "Réapprovisionnement des marchands et réglages d'assurance.", "jp-JP": "商人の在庫更新周期と保険関連の設定。"},
    "Feature.HeaderDesc.Independent": {"zh-CN": "MG-Mod 独立商人、物品、预设与存档开关。", "en-US": "Toggles for MG-Mod independent traders, items, presets, and profiles.", "ru-RU": "Включение независимых торговцев, предметов, пресетов и профилей MG-Mod.", "fr-FR": "Activation des marchands, objets, préréglages et profils indépendants de MG-Mod.", "jp-JP": "MG-Mod独立商人・アイテム・プリセット・プロフィールのスイッチ。"},
    "Feature.HeaderDesc.Other": {"zh-CN": "子弹数据、钥匙分类与实时跳蚤。", "en-US": "Bullet data, key organization, and real-time flea market.", "ru-RU": "Данные патронов, сортировка ключей и барахолка в реальном времени.", "fr-FR": "Données de munitions, organisation des clés et marché en temps réel.", "jp-JP": "弾丸データ、鍵の分類、リアルタイムフリーマーケット。"},
    "ContainerItem.Desc.BallisticPlateCase": {"zh-CN": "存放防弹插板的箱子。开启扩容后可自定义格子宽高。", "en-US": "A container for armor plates. With expansion enabled, you can customize its grid size.", "ru-RU": "Контейнер для бронепластин. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un conteneur pour plaques balistiques. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "防弾プレート用のコンテナ。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.GingyKeychain": {"zh-CN": "存放钥匙与挂饰的钥匙链。开启扩容后可自定义格子宽高。", "en-US": "A keychain for keys and trinkets. With expansion enabled, you can customize its grid size.", "ru-RU": "Брелок для ключей и безделушек. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un porte-clés pour clés et breloques. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "鍵や装飾品用のキーチェーン。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.HolodilnickThermalBag": {"zh-CN": "存放药品与食物的保温袋。开启扩容后可自定义格子宽高。", "en-US": "An insulated bag for medical supplies and food. With expansion enabled, you can customize its grid size.", "ru-RU": "Термосумка для медикаментов и еды. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un sac isotherme pour médicaments et nourriture. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "医薬品や食料用の保温バッグ。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.THICCWeaponCase": {"zh-CN": "存放武器与改装件的大型箱子。开启扩容后可自定义格子宽高。", "en-US": "A large case for weapons and weapon mods. With expansion enabled, you can customize its grid size.", "ru-RU": "Большой кейс для оружия и обвесов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une grande mallette pour armes et accessoires d'armes. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "武器やカスタムパーツ用の大型ケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.THICCItemCase": {"zh-CN": "存放各类物品的大型箱子。开启扩容后可自定义格子宽高。", "en-US": "A large case for assorted items. With expansion enabled, you can customize its grid size.", "ru-RU": "Большой кейс для различных предметов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une grande mallette pour objets divers. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "様々なアイテム用の大型ケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.WZWallet": {"zh-CN": "存放货币的钱包。开启扩容后可自定义格子宽高。", "en-US": "A wallet for money. With expansion enabled, you can customize its grid size.", "ru-RU": "Кошелёк для денег. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un portefeuille pour l'argent. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "通貨用の財布。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.StreamerItemCase": {"zh-CN": "存放主播战利品的箱子。开启扩容后可自定义格子宽高。", "en-US": "A case for streamer loot. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для лута стримера. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour butin de streamer. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "ストリーマーの戦利品用ケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.MedicineCase": {"zh-CN": "存放医疗用品的医疗箱。开启扩容后可自定义格子宽高。", "en-US": "A case for medical supplies. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для медикаментов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour fournitures médicales. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "医療用品用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.SICCPouch": {"zh-CN": "存放钥匙、货币等贵重物品的安全包。开启扩容后可自定义格子宽高。", "en-US": "A secure pouch for valuables such as keys and money. With expansion enabled, you can customize its grid size.", "ru-RU": "Защищённая сумка для ценных вещей (ключей, денег и т.д.). При включённом расширении можно настроить размер сетки.", "fr-FR": "Une pochette sécurisée pour objets de valeur (clés, argent, etc.). Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "鍵・通貨などの貴重品用セキュアポーチ。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.LuckyScavJunkBox": {"zh-CN": "存放杂物与材料的垃圾箱。开启扩容后可自定义格子宽高。", "en-US": "A junk box for miscellaneous items and materials. With expansion enabled, you can customize its grid size.", "ru-RU": "Ящик для хлама и материалов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un coffre à bric-à-brac et matériaux. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "ジャンクや素材用のジャンクボックス。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.MagazineCase": {"zh-CN": "存放弹匣的弹匣箱。开启扩容后可自定义格子宽高。", "en-US": "A case for magazines. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для магазинов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour chargeurs. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "マガジン用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.AmmunitionCase": {"zh-CN": "存放弹药的弹药箱。开启扩容后可自定义格子宽高。", "en-US": "A case for ammunition. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для патронов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour munitions. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "弾薬用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.PistolCase": {"zh-CN": "存放手枪的手枪箱。开启扩容后可自定义格子宽高。", "en-US": "A case for pistols. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для пистолетов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour pistolets. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "拳銃用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.GrenadeCase": {"zh-CN": "存放手雷的手雷箱。开启扩容后可自定义格子宽高。", "en-US": "A case for grenades. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для гранат. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour grenades. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "手榴弾用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.DocumentsCase": {"zh-CN": "存放文件与证件的文件箱。开启扩容后可自定义格子宽高。", "en-US": "A case for documents and papers. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для документов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour documents. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "書類や証明書用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.WeaponCase": {"zh-CN": "存放武器的武器箱。开启扩容后可自定义格子宽高。", "en-US": "A case for weapons. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для оружия. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour armes. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "武器用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.InjectorCase": {"zh-CN": "存放注射器与药剂的针剂箱。开启扩容后可自定义格子宽高。", "en-US": "A case for injectors and stimulants. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для шприцов и стимуляторов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour injecteurs et stimulants. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "インジェクターや薬剤用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.ItemCase": {"zh-CN": "存放各类物品的物品箱。开启扩容后可自定义格子宽高。", "en-US": "A case for assorted items. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для различных предметов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour objets divers. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "様々なアイテム用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.DogtagCase": {"zh-CN": "存放狗牌的狗牌箱。开启扩容后可自定义格子宽高。", "en-US": "A case for dogtags. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для жетонов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour plaques d'identification. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "ドッグタグ用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.SimpleWallet": {"zh-CN": "存放货币的简易钱包。开启扩容后可自定义格子宽高。", "en-US": "A simple wallet for money. With expansion enabled, you can customize its grid size.", "ru-RU": "Простой кошелёк для денег. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un simple portefeuille pour l'argent. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "通貨用のシンプルな財布。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.KeycardHolderCase": {"zh-CN": "存放门禁卡的门禁卡盒。开启扩容后可自定义格子宽高。", "en-US": "A holder for access keycards. With expansion enabled, you can customize its grid size.", "ru-RU": "Футляр для ключ-карт. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un étui pour cartes d'accès. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "アクセスキーカード用ホルダー。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.KeyTool": {"zh-CN": "存放钥匙的钥匙工具。开启扩容后可自定义格子宽高。", "en-US": "A tool for carrying keys. With expansion enabled, you can customize its grid size.", "ru-RU": "Ключница. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un outil pour porter des clés. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "鍵収納用のキーツール。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
    "ContainerItem.Desc.MoneyCase": {"zh-CN": "存放货币的钱箱。开启扩容后可自定义格子宽高。", "en-US": "A case for money. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для денег. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour l'argent. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "通貨用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
}


def run():
    for lang in LANGS:
        path = os.path.join(I18N_DIR, f'{lang}.json')
        with open(path, encoding='utf-8', newline='') as f:
            text = f.read()
        lines = text.split('\n')  # 每行可能带 \r（CRLF 文件）
        per_section = {}
        for key in DATA:
            per_section.setdefault(key.split('.')[0], []).append(key)
        for sec, keys in per_section.items():
            # 幂等：跳过已存在的键行（重跑不会重复插入）
            existing = {ln.split('"')[1] for ln in lines
                        if ln.startswith('    "') and '": "' in ln}
            keys = [k for k in keys if k[len(sec) + 1:] not in existing]
            if not keys:
                continue
            # 定位 section 起始
            start = next(i for i, l in enumerate(lines) if l.startswith(f'  "{sec}": {{'))
            # 定位该 section 结束（下一个 2 空格缩进的 "}," 或 "}"；先去除行尾 \r）
            end = None
            for i in range(start + 1, len(lines)):
                if re.match(r'^  \},?$', lines[i].rstrip('\r')):
                    end = i
                    break
            if end is None:
                raise SystemExit(f'{lang}: section {sec} 未找到结束符')
            # 上一个键行补逗号（逗号加在行尾 \r 之前，保持 CRLF）
            prev = lines[end - 1]
            if prev.rstrip('\r').endswith('"') and not prev.rstrip('\r').endswith('",'):
                lines[end - 1] = prev.rstrip('\r') + ',\r'
            # 生成新键行（4 空格缩进 + 行尾 \r，与全文件 CRLF 一致）
            new_lines = []
            for idx, key in enumerate(keys):
                value = DATA[key][lang]
                value = json.dumps(value, ensure_ascii=False)
                comma = ',' if idx < len(keys) - 1 else ''
                new_lines.append(f'    "{key[len(sec) + 1:]}": {value}{comma}\r')
            lines[end:end] = new_lines
        # 写入：utf-8 无 BOM（原文件无 BOM），保留 CRLF
        with open(path, 'w', encoding='utf-8', newline='') as f:
            f.write('\n'.join(lines))
        # 合法性校验
        with open(path, encoding='utf-8-sig') as f:
            json.load(f)
        print(f'{lang}: 键 {len(DATA)} 个，JSON 合法')

if __name__ == '__main__':
    run()
