# -*- coding: utf-8 -*-
"""MGModEditor 功能描述 Tier-2 翻译数据（分组标题 22 + 容器名 23 = 45 键 × 5 语言）。
被 tools/gen_feature_desc_i18n.py 构建脚本读取合并进 DATA。"""

TIER2 = {
# ---------- 分组标题 22 ----------
"Raid.HeaderDesc.AI": {
  "zh-CN": "AI 相关设置：血量、刷新数量、阵营比例、名字池与 PMC 行为。",
  "en-US": "AI settings: health, spawn numbers, faction ratios, name pool, and PMC behavior.",
  "ru-RU": "Настройки AI: здоровье, количество спавна, соотношение фракций, имена и поведение PMC.",
  "fr-FR": "Réglages IA : santé, apparitions, ratios de factions, noms et comportement des PMC.",
  "jp-JP": "AI関連の設定：体力、出現数、陣営比率、名前プール、PMCの行動。",
},
"Raid.HeaderDesc.DefaultOptions": {
  "zh-CN": "自定义战局默认的 AI 数量、难度、BOSS 与 SCAV 行为。",
  "en-US": "Customizes default raid options: AI amount, difficulty, bosses, and Scav behavior.",
  "ru-RU": "Настройка параметров рейда по умолчанию: количество AI, сложность, боссы и поведение Scav.",
  "fr-FR": "Personnalise les options de raid par défaut : nombre d'IA, difficulté, boss et comportement des Scavs.",
  "jp-JP": "レイドのデフォルト設定をカスタマイズ：AI数、難易度、ボス、Scavの行動。",
},
"Raid.HeaderDesc.Raid": {
  "zh-CN": "战局时长、BOSS 刷新、空投、撤离与 SCAV 相关设置。",
  "en-US": "Raid duration, boss spawns, airdrops, extracts, and Scav settings.",
  "ru-RU": "Длительность рейда, спавн боссов, аирдропы, выходы и настройки Scav.",
  "fr-FR": "Durée du raid, apparitions de boss, largages, sorties et réglages Scav.",
  "jp-JP": "レイド時間、ボス出現、エアドロップ、脱出、Scav関連の設定。",
},
"Raid.HeaderDesc.Weather": {
  "zh-CN": "战局天气表现：全局模式、云量、风、雨与雾。",
  "en-US": "Raid weather: global mode, clouds, wind, rain, and fog.",
  "ru-RU": "Погода в рейде: глобальный режим, облачность, ветер, дождь и туман.",
  "fr-FR": "Météo des raids : mode global, nuages, vent, pluie et brouillard.",
  "jp-JP": "レイドの天候：グローバルモード、雲量、風、雨、霧。",
},
"Raid.HeaderDesc.Resources": {
  "zh-CN": "全局与分地图的战利品刷新倍率。",
  "en-US": "Global and per-map loot spawn multipliers.",
  "ru-RU": "Множители спавна лута глобально и по картам.",
  "fr-FR": "Multiplicateurs d'apparition du butin, globaux et par carte.",
  "jp-JP": "全体・マップ別の戦利品出現倍率。",
},
"Raid.HeaderDesc.MapInsurance": {
  "zh-CN": "按地图开关物品的保险返还。",
  "en-US": "Toggles insurance returns per map.",
  "ru-RU": "Включение страхового возврата предметов по картам.",
  "fr-FR": "Active le retour d'assurance des objets par carte.",
  "jp-JP": "マップごとの保険返却のオン/オフ。",
},
"Develop.HeaderDesc.BaseAttributes": {
  "zh-CN": "角色基础能力：装卸速度、技能经验、负重限制等。",
  "en-US": "Basic character stats: reload speed, skill experience, carry limits, etc.",
  "ru-RU": "Базовые параметры персонажа: скорость перезарядки, опыт навыков, лимиты веса и т.д.",
  "fr-FR": "Capacités de base du personnage : rechargement, expérience de compétence, limites de charge, etc.",
  "jp-JP": "キャラクターの基礎能力：リロード速度、スキル経験値、重量制限など。",
},
"Develop.HeaderDesc.WeaponOpt": {
  "zh-CN": "武器相关：配件兼容、故障、耐久与弹匣容量。",
  "en-US": "Weapon settings: attachment compatibility, malfunctions, durability, and magazine capacity.",
  "ru-RU": "Настройки оружия: совместимость модулей, осечки, прочность и вместимость магазинов.",
  "fr-FR": "Réglages d'armes : compatibilité des accessoires, pannes, durabilité et capacité des chargeurs.",
  "jp-JP": "武器関連：アタッチメント互換、故障、耐久度、マガジン容量。",
},
"Develop.HeaderDesc.HelmetOpt": {
  "zh-CN": "头盔的兼容性、负面效果与负重。",
  "en-US": "Helmet compatibility, debuffs, and weight.",
  "ru-RU": "Шлемы: совместимость, негативные эффекты и вес.",
  "fr-FR": "Casques : compatibilité, malus et poids.",
  "jp-JP": "ヘルメットの互換性、デバフ、重量。",
},
"Develop.HeaderDesc.RigArmorOpt": {
  "zh-CN": "护甲与弹挂的兼容性、负面效果、负重与耐久。",
  "en-US": "Armor and rigs: compatibility, debuffs, weight, and durability.",
  "ru-RU": "Броня и разгрузки: совместимость, негативные эффекты, вес и прочность.",
  "fr-FR": "Armures et rigs : compatibilité, malus, poids et durabilité.",
  "jp-JP": "アーマーとリグの互換性、デバフ、重量、耐久度。",
},
"Develop.HeaderDesc.PlateCarrierOpt": {
  "zh-CN": "防弹插板与内衬的耐久、行动惩罚与负重。",
  "en-US": "Armor plates and liners: durability, movement penalties, and weight.",
  "ru-RU": "Бронепластины и подкладки: прочность, штрафы к движению и вес.",
  "fr-FR": "Plaques et doublures balistiques : durabilité, pénalités de mouvement et poids.",
  "jp-JP": "防弾プレートとライナーの耐久度、行動ペナルティ、重量。",
},
"Develop.HeaderDesc.BackpackOpt": {
  "zh-CN": "背包的嵌套、体积、负面效果与负重。",
  "en-US": "Backpacks: nesting, size, debuffs, and weight.",
  "ru-RU": "Рюкзаки: вложение, размер, негативные эффекты и вес.",
  "fr-FR": "Sacs à dos : imbrication, taille, malus et poids.",
  "jp-JP": "バックパックの入れ子、サイズ、デバフ、重量。",
},
"Develop.HeaderDesc.EnchantOpt": {
  "zh-CN": "武器与护甲的基础属性强化。",
  "en-US": "Base stat enhancements for weapons and armor.",
  "ru-RU": "Усиление базовых характеристик оружия и брони.",
  "fr-FR": "Renforcement des statistiques de base des armes et armures.",
  "jp-JP": "武器とアーマーの基礎ステータス強化。",
},
"Develop.HeaderDesc.InsuranceOpt": {
  "zh-CN": "安全箱（保险箱）的扩容、兼容与负重。",
  "en-US": "Secure containers: expansion, item compatibility, and weight.",
  "ru-RU": "Защищённые контейнеры: расширение, совместимость предметов и вес.",
  "fr-FR": "Conteneurs sécurisés : agrandissement, compatibilité d'objets et poids.",
  "jp-JP": "セキュアコンテナの拡張、収納互換、重量。",
},
"Develop.HeaderDesc.ItemAttrOpt": {
  "zh-CN": "热成像、钥匙与医疗物品的属性调整。",
  "en-US": "Item attributes: thermals, keys, and medical items.",
  "ru-RU": "Свойства предметов: тепловизоры, ключи и медикаменты.",
  "fr-FR": "Attributs d'objets : thermiques, clés et objets médicaux.",
  "jp-JP": "アイテム属性：熱成像、鍵、医療アイテム。",
},
"Develop.HeaderDesc.WarehouseOpt": {
  "zh-CN": "弹药与货币的堆叠数量、物品全检视。",
  "en-US": "Ammo and money stack sizes, and full item inspection.",
  "ru-RU": "Размер стака патронов и денег, полный осмотр предметов.",
  "fr-FR": "Tailles de pile des munitions et de l'argent, inspection complète.",
  "jp-JP": "弾薬・通貨のスタック数、全アイテム検査。",
},
"Develop.HeaderDesc.QuestSystem": {
  "zh-CN": "任务重置、条件简化与 3X4 任务链。",
  "en-US": "Quest resets, simplified conditions, and the 3X4 quest chain.",
  "ru-RU": "Сброс заданий, упрощение условий и цепочка заданий 3X4.",
  "fr-FR": "Réinitialisation des quêtes, conditions simplifiées et chaîne 3X4.",
  "jp-JP": "クエストのリセット、条件簡略化、3X4クエストチェーン。",
},
"Develop.HeaderDesc.Hideout": {
  "zh-CN": "藏身处升级、生产、供电与健身房相关。",
  "en-US": "Hideout upgrades, production, power, and the gym.",
  "ru-RU": "Улучшение убежища, производство, энергопитание и спортзал.",
  "fr-FR": "Améliorations de la planque, production, électricité et coin sport.",
  "jp-JP": "Hideoutのアップグレード、生産、電力、ジム。",
},
"Economy.HeaderDesc.Flea": {
  "zh-CN": "跳蚤市场的交易、出售、购买与税率设置。",
  "en-US": "Flea Market trading, selling, buying, and tax settings.",
  "ru-RU": "Настройки барахолки: сделки, продажа, покупка и налоги.",
  "fr-FR": "Marché aux puces : transactions, ventes, achats et taxes.",
  "jp-JP": "フリーマーケットの取引、販売、購入、税率の設定。",
},
"Economy.HeaderDesc.Trader": {
  "zh-CN": "商人供货周期与保险相关设置。",
  "en-US": "Trader restock intervals and insurance settings.",
  "ru-RU": "Период обновления запасов торговцев и настройки страховки.",
  "fr-FR": "Réapprovisionnement des marchands et réglages d'assurance.",
  "jp-JP": "商人の在庫更新周期と保険関連の設定。",
},
"Feature.HeaderDesc.Independent": {
  "zh-CN": "MG-Mod 独立商人、物品、预设与存档开关。",
  "en-US": "Toggles for MG-Mod independent traders, items, presets, and profiles.",
  "ru-RU": "Включение независимых торговцев, предметов, пресетов и профилей MG-Mod.",
  "fr-FR": "Activation des marchands, objets, préréglages et profils indépendants de MG-Mod.",
  "jp-JP": "MG-Mod独立商人・アイテム・プリセット・プロフィールのスイッチ。",
},
"Feature.HeaderDesc.Other": {
  "zh-CN": "子弹数据、钥匙分类与实时跳蚤。",
  "en-US": "Bullet data, key organization, and real-time flea market.",
  "ru-RU": "Данные патронов, сортировка ключей и барахолка в реальном времени.",
  "fr-FR": "Données de munitions, organisation des clés et marché en temps réel.",
  "jp-JP": "弾丸データ、鍵の分類、リアルタイムフリーマーケット。",
},
# ---------- 容器名 23 ----------
"ContainerItem.Desc.BallisticPlateCase": {"zh-CN": "存放防弹插板的箱子。开启扩容后可自定义格子宽高。", "en-US": "A container for armor plates. With expansion enabled, you can customize its grid size.", "ru-RU": "Контейнер для бронепластин. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un conteneur pour plaques balistiques. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "防弾プレート用のコンテナ。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.GingyKeychain": {"zh-CN": "存放钥匙与挂饰的钥匙链。开启扩容后可自定义格子宽高。", "en-US": "A keychain for keys and trinkets. With expansion enabled, you can customize its grid size.", "ru-RU": "Брелок для ключей и безделушек. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un porte-clés pour clés et breloques. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "鍵や装飾品用のキーチェーン。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.HolodilnickThermalBag": {"zh-CN": "存放药品与食物的保温袋。开启扩容后可自定义格子宽高。", "en-US": "An insulated bag for medical supplies and food. With expansion enabled, you can customize its grid size.", "ru-RU": "Термосумка для медикаментов и еды. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un sac isotherme pour médicaments et nourriture. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "医薬品や食料用の保温バッグ。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.THICCWeaponCase": {"zh-CN": "存放武器与改装件的大型箱子。开启扩容后可自定义格子宽高。", "en-US": "A large case for weapons and weapon mods. With expansion enabled, you can customize its grid size.", "ru-RU": "Большой кейс для оружия и обвесов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une grande mallette pour armes et accessoires d'armes. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "武器やカスタムパーツ用の大型ケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.THICCItemCase": {"zh-CN": "存放各类物品的大型箱子。开启扩容后可自定义格子宽高。", "en-US": "A large case for assorted items. With expansion enabled, you can customize its grid size.", "ru-RU": "Большой кейс для различных предметов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une grande mallette pour objets divers. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "様々なアイテム用の大型ケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.WZWallet": {"zh-CN": "存放货币的钱包。开启扩容后可自定义格子宽高。", "en-US": "A wallet for money. With expansion enabled, you can customize its grid size.", "ru-RU": "Кошелёк для денег. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un portefeuille pour l'argent. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "通貨用の財布。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.StreamerItemCase": {"zh-CN": "存放主播战利品的箱子。开启扩容后可自定义格子宽高。", "en-US": "A case for streamer loot. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для лута стримера. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour butin de streamer. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "ストリーマーの戦利品用ケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.MedicineCase": {"zh-CN": "存放医疗用品的医疗箱。开启扩容后可自定义格子宽高。", "en-US": "A case for medical supplies. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для медикаментов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour fournitures médicales. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "医療用品用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.SICCPouch": {"zh-CN": "存放钥匙、货币等贵重物品的安全包。开启扩容后可自定义格子宽高。", "en-US": "A secure pouch for valuables such as keys and money. With expansion enabled, you can customize its grid size.", "ru-RU": "Защищённая сумка для ценных вещей (ключей, денег и т.д.). При включённом расширении можно настроить размер сетки.", "fr-FR": "Une pochette sécurisée pour objets de valeur (clés, argent, etc.). Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "鍵・通貨などの貴重品用セキュアポーチ。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.LuckyScavJunkBox": {"zh-CN": "存放杂物与材料的垃圾箱。开启扩容后可自定义格子宽高。", "en-US": "A junk box for miscellaneous items and materials. With expansion enabled, you can customize its grid size.", "ru-RU": "Ящик для хлама и материалов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un coffre à bric-à-brac et matériaux. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "ジャンクや素材用のジャンクボックス。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.MagazineCase": {"zh-CN": "存放弹匣的弹匣箱。开启扩容后可自定义格子宽高。", "en-US": "A case for magazines. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для магазинов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour chargeurs. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "マガジン用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.AmmunitionCase": {"zh-CN": "存放弹药的弹药箱。开启扩容后可自定义格子宽高。", "en-US": "A case for ammunition. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для патронов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour munitions. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "弾薬用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.PistolCase": {"zh-CN": "存放手枪的手枪箱。开启扩容后可自定义格子宽高。", "en-US": "A case for pistols. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для пистолетов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour pistolets. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "拳銃用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.GrenadeCase": {"zh-CN": "存放手雷的手雷箱。开启扩容后可自定义格子宽高。", "en-US": "A case for grenades. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для гранат. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour grenades. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "手榴弾用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.DocumentsCase": {"zh-CN": "存放文件与证件的文件箱。开启扩容后可自定义格子宽高。", "en-US": "A case for documents and papers. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для документов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour documents. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "書類や証明書用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.WeaponCase": {"zh-CN": "存放武器的武器箱。开启扩容后可自定义格子宽高。", "en-US": "A case for weapons. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для оружия. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour armes. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "武器用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.InjectorCase": {"zh-CN": "存放注射器与药剂的针剂箱。开启扩容后可自定义格子宽高。", "en-US": "A case for injectors and stimulants. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для шприцов и стимуляторов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour injecteurs et stimulants. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "インジェクターや薬剤用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.ItemCase": {"zh-CN": "存放各类物品的物品箱。开启扩容后可自定义格子宽高。", "en-US": "A case for assorted items. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для различных предметов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour objets divers. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "様々なアイテム用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.DogtagCase": {"zh-CN": "存放狗牌的狗牌箱。开启扩容后可自定义格子宽高。", "en-US": "A case for dogtags. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для жетонов. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour plaques d'identification. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "ドッグタグ用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.SimpleWallet": {"zh-CN": "存放货币的简易钱包。开启扩容后可自定义格子宽高。", "en-US": "A simple wallet for money. With expansion enabled, you can customize its grid size.", "ru-RU": "Простой кошелёк для денег. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un simple portefeuille pour l'argent. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "通貨用のシンプルな財布。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.KeycardHolderCase": {"zh-CN": "存放门禁卡的门禁卡盒。开启扩容后可自定义格子宽高。", "en-US": "A holder for access keycards. With expansion enabled, you can customize its grid size.", "ru-RU": "Футляр для ключ-карт. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un étui pour cartes d'accès. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "アクセスキーカード用ホルダー。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.KeyTool": {"zh-CN": "存放钥匙的钥匙工具。开启扩容后可自定义格子宽高。", "en-US": "A tool for carrying keys. With expansion enabled, you can customize its grid size.", "ru-RU": "Ключница. При включённом расширении можно настроить размер сетки.", "fr-FR": "Un outil pour porter des clés. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "鍵収納用のキーツール。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
"ContainerItem.Desc.MoneyCase": {"zh-CN": "存放货币的钱箱。开启扩容后可自定义格子宽高。", "en-US": "A case for money. With expansion enabled, you can customize its grid size.", "ru-RU": "Кейс для денег. При включённом расширении можно настроить размер сетки.", "fr-FR": "Une mallette pour l'argent. Avec l'agrandissement, vous pouvez personnaliser la taille de la grille.", "jp-JP": "通貨用のケース。拡張を有効にするとグリッドサイズをカスタマイズできます。"},
}
